---
development:
  cloud_name: chullman
  api_key: <%= ENV['cloudinary_api_key'] %>
  api_secret: <%= ENV['cloudinary_api_secret'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: chullman
  api_key: <%= ENV['cloudinary_api_key'] %>
  api_secret: <%= ENV['cloudinary_api_secret'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: chullman
  api_key: <%= ENV['cloudinary_api_key'] %>
  api_secret: <%= ENV['cloudinary_api_secret'] %>
  enhance_image_tag: true
  static_image_support: false
